#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

case $BLOCK_BUTTON in
	3) notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
🔌: charging
⚡: charged
❗: battery very low!
- Scroll to change adjust xbacklight." ;;
	4) light -A 5 ;;
	5) light -U 5 ;;
	6) foot -e "$EDITOR" "$0" ;;
esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	
	   case "$(cat "$battery/status" 2>&1)" in
        "Full") status="" ;;
        "Discharging") status="" ;;
        "Charging") status="" ;;
        "Not charging") status="🛑" ;;
        "Unknown") status="♻️" ;;
        *) exit 1 ;;
    esac
    
    
	capacity="$(cat "$battery/capacity" 2>&1)"
	# Will make a warn variable if discharging and low
	
	    [ "$status" = "" ] && [ "$capacity" -le 25 ] && warn="❗"    
    
if [ "$capacity" -gt "95" ] && [ "$status" = "" ] ; then
    status=""
elif [ "$capacity" -gt "75" ] && [ "$status" = "" ]; then
    status=""
elif [ "$capacity" -gt "50" ] && [ "$status" = "" ]; then
    status=""
elif [ "$capacity" -gt "25" ] && [ "$status" = "" ] ; then
    status=""
elif [ "$capacity" -gt "10" ] && [ "$status" = "" ]; then
    status=""
fi

	printf "%s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && printf "\\n"
