#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f foot  pulsemixer ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5  ;;
	5)pulsemixer --change-volume -5 ;;
	2) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

vol="$(pulsemixer --get-volume | cut -d ' ' -f 1)"

mute="$(pulsemixer --get-mute)"

# If muted, print 🔇 and exit.
[ "$mute" != "1" ] && echo 🔇

vol="${vol#Volume: }"
split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}
vol="$(split "$vol" ".")"
vol="${vol##0}"

case 1 in
	$((vol >= 70)) ) icon="🔊" ;;
	$((vol >= 30)) ) icon="🔉" ;;
	$((vol >= 1)) ) icon="🔈" ;;
	* ) echo 🔇 ;;
esac

echo "$icon$vol%"
